### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by alexaderramos** [binary-cats/laravel-sku#16]
You could place an option to be able to place a prefix in the options to generate the sku, for example, in some cases it is required to place a prefix in a table that only contains numerical values.

**`->prefix('PREFIX')
`**
```
    /**
     * Get the options for generating the Sku.
     *
     * @return BinaryCats\Sku\SkuOptions
     */
    public function skuOptions() : SkuOptions
    {
        return SkuOptions::make()
           ->prefix('PREFIX')
            ->from(['label', 'other'])
            ->target('sku')
            ->using('-')
            ->forceUnique(true)
            ->generateOnCreate(true)
            ->refreshOnUpdate(false);
    }
```
Thanks, I loved this sku's generator

**Comment by cyrillkalita** [comment]
@alexaderramos is this to affect the format of the SKU itself?
In which case, you may register a custom SKU Generator:

in `config/laravel-sku.php`
```
    'generator' => \App\Components\MySkuGenerator::class, 
```

and then overload any method you want from `SkuGenerator`. Would that help?
