### ISSUE TITLE
Crash when using the Trait HasSku in the Model

### ISSUE THREAD

**Issue by AmrSubZero** [binary-cats/laravel-sku#18]
**Infinity Loop** that ends with `500 error page` while using the Trait `HasSku` in `Product` Model

Laravel Version : `Laravel Framework 8.58.0`

```
use BinaryCats\Sku\HasSku;

class Product extends Model
{
    use HasSku;
}
```

When i remove the Trait `HasSku` from the Model, it's working, but not with it.

Config `laravel-sku.php` :

```
'default' => [
     'source' => 'title',
```

Products Table :

```
| id  	| title 	| sku 	| ... 	|
|-----	|-------	|-----	|-----	|
| ... 	| ...   	| ... 	| ... 	|
```

**_Notice:_** i installed this dependency while i was having all products without sku, all of them have `null` sku, but that shouldn't be a problem.

Installation :

```
/> composer require binary-cats/laravel-sku
/> php artisan vendor:publish --provider="BinaryCats\Sku\SkuServiceProvider" --tag="config"
```

**Comment by nickfls** [comment]
@AmrSubZero what do the logs show for this error 500?

**Comment by limsocheat** [comment]
I have the same issue. App stop freeze in white screen when accessing to product which use HasSku Trait

**Comment by cyrillkalita** [comment]
@limsocheat 
is there anything written in the logs? Error 500 should really be reflected in the log
