### ISSUE TITLE
Model Result Doesn't Display after applying the HasSku trait

### ISSUE THREAD

**Issue by aeadedoyin** [binary-cats/laravel-sku#5]
Thanks for this dope package!!!
Gave it a star immediately I found it.

So I have a table of products I want to generate SKUs, 
But it doesn't work even after installing and configuring as below:

//config
```
'default' => [
        'source' => ['id', 'name', 'type', 'created_at'],
        'field' => 'sku',
        'separator' => '-',
        'unique' => true,
        'generate_on_create' => true,
        'generate_on_update' => true,
    ],
```

//model
```
use HasSku;

    public function skuOptions(): SkuOptions
    {
        return SkuOptions::make()
            ->from(['id', 'name', 'type'])
            ->target('sku')
            ->using('-')
            ->forceUnique(true)
            ->generateOnCreate(true)
            ->refreshOnUpdate(true);
    }

   protected $fillable = [
        'name', 'sku', 'description', 'content', 'type', 'price', 'featured_image'
    ];
```

//controller :: So that it populates the sku
```
        $products = Products::all();
        foreach ($products as $product) {
            $product->save(); //update
        }
        return $products;
```

**Comment by cyrillkalita** [comment]
@aeadedoyin easy; SKU will be regenerated _when the fields it is based on are dirty_.

Here you are just _re-saving_ the model, without any changes, the fields are not updated in any way, thus not warranting SKU  recalculation.

I understand that you want to populate missing SKUs in your Product table.

How about this?

```php

use \BinaryCats\Sku\Concerns\SkuGenerator;

Products::get()->each(function($product){
    $product->update([
        'sku' => SkuGenerator($product)->render()
    ]);
})
```

**Comment by aeadedoyin** [comment]
Thanks @cyrillkalita 
Since I didn't hear from you. (Busy I guess.) 
I already used [`Str::orderedUuid();`]
